name: Release

on:
  push:
    branches:
      - master
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          path: ./composeApp/build/dist/wasmJs/productionExecutable/
          if-no-files-found: error
          retention-days: 1
          overwrite: true

      - name: Post Artifact ID
        run:  echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'

      - name: Get version
        id: get_version
        run: |
          version=$(./gradlew -q printVersion)
          echo "version=$version" >> $GITHUB_ENV

      - name: Download Artifact by ID
        run: |
          curl -L -o ${{ runner.temp }}/artifact/artifact.zip -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}/zip"

      - name: List Downloaded Files
        run: ls -l ${{ runner.temp }}/artifact/

      - name: Unzip Artifact
        run: unzip ${{ runner.temp }}/artifact/artifact.zip -d ${{ runner.temp }}/artifact/unpacked/


      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
         folder: ${{ runner.temp }}/artifact/unpacked/
